file_format: "1"
id: 4c
name: 4c
type: shield
url: https://github.com/compressionKeyboards/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - 4c_left
  - 4c_right
